### ISSUE TITLE
Use of uninitialized value $git_ref in concatenation (.) or string at /data/mysociety/bin/deploy-vhost

### ISSUE THREAD

**Issue by stevenday** [mysociety/misc-scripts#13]
I see this error a lot, relating to lines 547, 552, 673 of deploy-vhost and I don't know what to do about it, but I presume it's a bug?

Possibly related - I believe that this causes problems when deploying from a private repo with an updated config file. My (rudimentary) reading of https://github.com/mysociety/misc-scripts/blob/32ca26a94c6024cb18b1bd96aea1bdae0b75082d/bin/deploy-vhost#L663-L673 suggests that it should compare the config file it builds from the .ugly template to the example file in the commit it's deploying. 

What I think actually happens is that it compares it to the example in the current checkout, i.e. the old one. This means that you can't deploy a site with new config values without some hackery.

**Comment by dracos** [comment]
You don't say which host it is, but I'm guessing it's passengerfocus and its config is slightly wrong – if you're using `private_git_repository`, then you need to use `private_conf_dir` for its config directory, not `conf_dir`. This dates from when something could have both a public and private repo (with their own config directories) as part of its deploy; presumably if only one public/private repo is present, it could/should check that the right config variable is present to match.

**Comment by stevenday** [comment]
Aha! I've fixed that in the PF config and it's removed the warning - thanks!
