### ISSUE TITLE
Upgrade bundled jslint

### ISSUE THREAD

**Issue by dracos** [mysociety/misc-scripts#31]
I've just written some JS for FMS that uses modern `const` etc and it is rejected by the jslint we currenty have. Upgrading should be okay, though it looks like I had to mangle it a bit last time for file input/output, so will need to check...

**Comment by dracos** [comment]
Want to go with jshint instead; 'installed' on leopard, but not cleanly, need a way to have it installed properly.

**Comment by sagepe** [comment]
I've added jshint to `packages.json`, added that together with `packages-lock.json` generated by an `npm install` to the repo and added `node-modules/` to `.gitignore`. Puppet will install these where needed on our servers, and we should be able to update easily in future by committing new versions of the package files.

**Comment by sagepe** [comment]
I think that everything required for this is now in place, so I'm closing.
